server:
  name: keeper-eureka
  port: 8761
  ip: host.docker.internal
  eureka:
    hostname: host.docker.internal
    prefer-ip: false
  logging:
    level: info
    filePath: ../logs/eureka/eureka.log