name: eureka-action-process
env:
  APPLICATION_NAME : "Keeper-Eureka"
on: 
  push:
    branches: 
      - prod

jobs:
  Keeper-eureka:
    defaults:
      run:
        working-directory: ./core

    runs-on: self-hosted
    
    steps:
      - name: PrintAppData
        run : |
          echo "Application name2: ${{ env.APPLICATION_NAME}}"

                 
        


