name: eureka-action-process
env:
  APPLICATION_NAME : "Keeper-Eureka"
on: 
  push:
    branches: 
      - prod

jobs:
  Keeper-eureka:

    runs-on: self-hosted
    
    steps:
      - name: PrintAppData
        run : |
          echo "Application name: ${{ env.APPLICATION_NAME}}"
          working-directory: ./app

                 
        


